---
title: "Einführung"
weight: 101
tags: ["signifikanz", "hypothesentest"]
---

Die [Ergebnisse der Korrelationsberechnungen](../../../LM3/chapter2/subchapter3/page-2-3-a/) können wir bisher nur auf die Stichprobe beziehen.

Wir wissen also in unserem Beispiel der [Pearson-Korrelation](../../glossar/pearsonsr/index.html), dass die die Präferenz für die CDU mit dem Alter einer Person positiv korreliert ($r=0.97$). Es handelt sich hierbei um eine sehr starke (fast perfekte) lineare Korrelation.

Nun soll aber in den Sozialwissenschaften nicht nur eine Aussage über eine (Zufalls-)Stichprobe getroffen werden, sondern die Aussage soll auf die Grundgesamtheit übertragen werden. Deshalb werden in den Sozialwissenschaften nicht [willkürliche](../../glossar/willkuerlicheauswahl/index.html) oder [bewusste Stichproben](../../glossar/bewussteauswahl/index.html) gezogen, sondern durch [zufallsbasierte](../../glossar/zufallsstichprobe/index.html) Verfahren Stichproben erhoben, um mithilfe der Wahrscheinlichkeitsrechnung Rückschlüsse auf die Grundgesamtheit führen zu können.

Um nun den [Inferenzschluss](../../glossar/inferenzstatistik/index.html) auf die Grundgesamtheit treffen zu können, müssen die Ergebnisse durch einen **Hypothesentest** auf Signifikanz überprüft werden. Deshalb werden diese **Hypothesentests** auch **Signifikanztests** genannt. In einem solchen **Hypothesentest** testen wir, wie wahrscheinlich ein angenommener Wert des Zusammenhangs zwischen zwei [Variablen](../../glossar/variable/index.html) ist. Also mathematisch gesprochen, ob ein Effekt in der Stichprobe zufällig entstanden sein kann und dieser in der Grundgesamtheit gar nicht vorliegt.

Statistische Testverfahren sind daher grundlegende Beurteilungsverfahren in der quantitativen Datenanalyse ([Inferenzstatistik](../../glossar/inferenzstatistik/index.html)). Statistische Tests werden benutzt, um die Wahrscheinlichkeiten anzugeben, dass die gesichtete Beobachtung (hier im Beispiel die ermittelte Korrelation zwischen *Alter* und *Präferenz* für die CDU) der Stichprobe auch wahrscheinlich in der Grundgesamtheit vorzufinden ist. Für das weitere Vorgehen nehmen wir nun an, dass unsere Stichprobe zufallsbasiert ausgewählt wurde und ausreichend groß ist. Um das Verständnis zu erleichtern, wurde eine kleine Datenmenge ausgewählt.

Um einen statistischen Test zu berechnen, muss zuerst eine **Nullhypothese** ($H_0$) sowie ihre **Alternativhypothese** ($H_A$) gebildet werden.

Diese Hypothesen sind Annahmen über die Verteilung einer Variable auf Basis der Stichprobe. In den Sozialwissenschaften wird die **Nullhypothese** meist als **Punkthypothese** verwendet: Der vermutete Zusammenhang/die vermutete Ausprägung wird als nicht vorhanden formuliert.

Die **Alternativhypothese** wird dann als Hypothese über die/den vermutete/n Differenz/Zusammenhang betrachtet. Dabei kann die **Alternativhypothese** als $\neq H_0$ formuliert sein oder als $>H_0 / <H_0$. In Abhängigkeit der Formulierung der **Alternativhypothese** wird entweder ein **einseitiger Test** oder ein **zweiseitiger Test** berechnet. Es wird getestet, ob eine gewisse Aussage zutrifft.

Je nach Verfahren und Verteilung einer Variablen können verschiedene Testverteilungen genutzt werden: zum Beispiel die [Normalverteilung](../../glossar/normalverteilung/index.html), [t-Verteilung](../../glossar/tverteilung/index.html) oder [z-Verteilung](../../glossar/zverteilung/index.html). Das Verfahren zum Prüfen ist dabei immer gleich und wird exemplarisch an der Normalverteilung vorgestellt.

Es wird nun zuerst der Unterschied zwischen einem **einseitigen** und **zweiseitigen Test** dargestellt, bevor die Begriffe der **Irrtumswahrscheinlichkeit** und **Vertrauenswahrscheinlichkeit** erläutert werden. Anschließend wird ein **Anwendungsbeispiel** berechnet.
