---
title: "Homoskedastizität"
---

Homoskedastizität ist eine Annahme der linearen Regression. Dies setzt somit voraus, dass die Varianzen der Residuen an allen Prädiktorwerte für die abhängige Variable gleich sein müssen. Die Streuung dieser darf mit zunehmenden oder abnehmenden Werten nicht größer/kleiner werden.
Sollte keine Homoskedastizität vorhanden sind, sind die Schätzer nicht zuverlässig. Das heißt, dass die Standardabweichung, das Konfidenzintervall und dadurch die Teststatistiken auf Signifikanz nicht interpretierbar sind.

{{% buttonShare href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}
