---
title: "Signifikanztest"
---

auch Hypothesentest genannt; Test der Inferenzstatistik; es wird getestet, inwieweit ein Zusammenhang in der Stichprobe auch in der Grundgesamtheit wahrscheinlich ist (->Inferenz); getestet wird die Nullhypothese (also das Gegenteil der Annahme muss widerlegt werden); Alternativhypothese beinhaltet theoretische Vermutung der Forscher*in; Entscheidung wird gegen Nullhypothese unter Irrtumswahrscheinlichkeit gefällt; Testgröße in Abhängigkeit der Verteilung (z.B. t-Test, F-Test oder z-Test); es wird zwischen einem einseitigen (Richtungstest) und zweiseitigen Signifikanztest (ungleich/gleich-Test) unterschieden.

{{% buttonGit href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonGit %}} 

{{% buttonGit href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-twitter\" %}} {{% /buttonGit %}}

{{% buttonGit href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonGit %}}
