---
title: "Varianz"
---
Streuungsmaß; Zeichen der Varianz $\sigma^2$; Summe der quadrierten Abweichungen der Werte vom Mittelwert; Einheit der Varianz ist nicht interpretierbar; Berechnung: $s^2=\sigma^2=\frac{1}{n} \ast \sum_{i=1}^n(x_i - \bar{x})^2$
Für die Berechnung einer Standardabweichung aus einer Stichprobe wird die Bessel-Korrektur angewendet ($\frac{1}{n-1}$):

$$s^2 = \frac{1}{n-1}* \sum_{i=1}^n (x_i - \bar{x})^2$$

{{% buttonShare href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}
