---
title: "Variationsweite"
weight: 301
tags: ["streumasse", "variationsweite", "spannweite"]
bibliography: [../../static/files/publications.bib]
suppress-bibliography: true
link-citations: true
# nocite: "@*" um einfach alle Angaben zu printen am Ende
csl: [../../static/files/apa.csl]
---

{{% buttonShare href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

Als **Variationsweite**, auch **Spannweite**, wird die Differenz zwischen dem größten (xmax) und dem kleinsten Wert (xmin) der Verteilung bezeichnet. Sie beschreibt die Größe des Bereichs, innerhalb derer sich die Daten befinden. **Variationsweite** wird teilweise auf Englisch als **Range** bezeichnet. Da es ein Minimum und Maximum geben muss, setzt die Variationsweite voraus, dass die Daten eine Rangordnung haben, also ordinalskaliert sind.

$$V=R=x_{max} – x_{min}$$

Im Beispiel von oben, der *Anzahl von politikwissenschaftlichen* Büchern, war:

$$x_{max}=31$$ und $$x_{min}=1$$

Hiermit erhalten die im konkreten Fall die *Variationsweite*:

$$V=R=x_{max} – x_{min}=31-1=30$$

{{% notice tip %}}
Siehe auch: @Gehring2009 [Kapitel 6.2.2].
{{% /notice %}}