---
title: "Standardabweichung"
weight: 304
tags: ["streumasse", "standardabweichung", "std"]
bibliography: [../../static/files/publications.bib]
suppress-bibliography: true
link-citations: true
# nocite: "@*" um einfach alle Angaben zu printen am Ende
csl: [../../static/files/apa.csl]
---

Die **Standardabweichung** ist die Wurzel der [Varianz](../../glossar/varianz/index.html), also die Wurzel der quadrierten durchschnittlichen Abweichung der Werte zum [Mittelwert](../../glossar/mittelwert/index.html). Diese ist wieder in der Maßeinheit der [Variablen](../../glossar/variable/index.html) zu interpretieren und wird deshalb auch häufiger genutzt. Die **Standardabweichung** gibt somit die durchschnittliche Abweichung der Werte zum Mittelwert an. Mit diesem Maß wird nicht die Abweichung einzelner Werte zum Mittelwert berechnet, sondern die durchschnittliche Größe der Abweichungen zum Mittelwert repräsentiert (Bortz/Schuster 2010: 31).

Berechnet wird die **Standardabweichung** bei einer Vollerhebung wie folgt:

$$\begin{align} \sigma &= \sqrt{\sigma^2} \\ &= \sqrt{\frac{1}{n} \ast \sum_{i=1}^n(x_i - \bar{x})^2} \\ &= \sqrt{\frac{\sum_{i=1}^n(x_i - \bar{x})^2}{n}} \end{align}$$

Bei der Anwendung einer Stichprobe gilt auch hier die Korrektur der Varianz um $\frac{1}{n-1}$:

$$\begin{align} s &= \sqrt{s^2} \\ &= \sqrt{\frac{1}{n-1} \ast \sum_{i=1}^n(x_i - \bar{x})^2} \\ &= \sqrt{\frac{\sum_{i=1}^n(x_i - \bar{x})^2}{n-1}} \\ \end{align}$$

Die **Standardabweichung** ist also vereinfacht gesprochen die Wurzel der [Varianz](../../glossar/varianz.index.hmtl).


Nehmen wir zur Illustration das Beispiel der Varianz aus einer Stichprobe auf.

In unserem Beispiel lag die Varianz bei:

$$s = 766666.67$$

Die **Standardabweichung** errechnet sich daher wie folgt:

$$\begin{align} s &= \sqrt{s^2} \\ &= \sqrt{766666.67} \\ &\approx 875.6 \end{align}$$

Durchschnittlich weichen also unsere Werte um $875.6$ Euro vom Mittelwert ab. Je höher die **Standardabweichung**, desto weiter streuen die Werte um den Mittelwert. Die Interpretation muss aber immer die Einheit berücksichtigen.

{{% notice tip %}}
Siehe auch: @Gehring2009 [Kapitel 6.2.5].
{{% /notice %}}
