---
title: "Einführung"
weight: 201
tags: ["mittelwertvergleich", "gruppenvergleich"]
bibliography: [../../static/files/publications.bib]
suppress-bibliography: true
link-citations: true
# nocite: "@*" um einfach alle Angaben zu printen am Ende
csl: [../../static/files/apa.csl]
---

{{% buttonGit href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonGit %}} 

{{% buttonGit href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonGit %}}

{{% buttonGit href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonGit %}}

{{% buttonGit href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonGit %}}

{{% buttonGit href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-twitter\" %}} {{% /buttonGit %}}

{{% buttonGit href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonGit %}}

Mit Mittelwertvergleichen werden also Zusammenhänge zwischen [nominalen](../../glossar/nominalskala/index.html) (Gruppenvariable, im Beispiel *Geschlecht*) und metrischen Variablen (im Beispiel *Einkommen*) getestet.

Für den **Mittelwertvergleich** gibt es mehrere Verfahren, die in Abhängigkeit der *Gruppenanzahl* der nominalen Variable und in Abhängigkeit der [Stichprobe](../../glossar/stichprobe/index.html) angewandt werden. Für einen **Mittelwertvergleich** zwischen *zwei Gruppen* wird der sogenannte **t-test (Mittelwertvergleich)** genutzt und für eine Untersuchung von *mehr als zwei Gruppen* der sogenannte **F-Test (Varianzanalyse)**.

Bei beiden genannten Verfahren wird nochmals unterschieden, ob die Stichproben **abhängig** oder **unabhängig** voneinander sind.

**Unabhängige Stichproben** liegen vor, wenn keine Zuordnung (zwischen den Befragten) möglich ist. Zum Beispiel, wenn wir untersuchen, ob männliche Befragte länger Fernsehen schauen als weibliche Befragte. Die Zusammensetzung der Männer in der einen Stichprobe ist unabhängig von der Zusammensetzung der Frauen in der anderen Stichprobe.

Eine **abhängige Stichprobe** (auch gepaarte/verbundene Stichprobe) liegt dann vor, wenn jedem Wert der einen Stichprobe eindeutig und sinnvoll ein Wert der anderen Stichprobe zugeordnet werden kann. So können wir zum Beispiel Partnerschaften (Zweierbeziehungen) befragen und eine Stichprobe zwischen den Partner:innen vergleichen. Hier können wir jeder:jedem Partner:in A eindeutig eine:einen Partner:in B zuordnen – also einen Fall aus der einen Stichprobe (alle Partner A) einem Fall aus der anderen (alle Partner B) zuordnen. Dies liegt auch vor, wenn wir von einem Individuum eine Messung zu mehreren Zeitpunkten untersuchen.

Es ergeben sich also für **Mittelwertvergleiche** vier verschiedene Testsituationen:

1. Vergleiche von zwei [unabhängigen Stichproben](../../glossar/unabhaengigestichprobe/index.html)

- statistischer Test: *t-Test für unabhängige Stichproben*

2. Vergleich von zwei [abhängigen Stichproben](../../glossar/abhaengigestichprobe/index.html)

- statistischer Test: *t-Test für abhängige Stichproben*

3. Vergleich von mehr als zwei [unabhängigen Stichproben](../../glossar/unabhaengigestichprobe/index.html)

- *einfaktorielle Varianzanalyse*

4. Vergleich von mehr als [abhängigen Stichproben](../../glossar/abhaengigestichprobe/index.html)

- *einfaktorielle Varianzanalyse mit Messwiederholungen*

Die häufigste Anwendung ist ein Gruppenvergleich zwischen *zwei* [unabhängigen Stichproben (t-Test)](../../glossar/unabhaengigestichprobe/index.html). Dieses Verfahren wird neben dem Verfahren für [abhängige Stichproben](../../glossar/abhaengigestichprobe/index.html) in diesem Lernmodul vorgestellt. Die Interpretation der anderen Verfahren ist ähnlich und kann mithilfe der empfohlenen Literatur selbstständig aufgearbeitet werden.

{{% notice tip %}}
Siehe auch: @Behnke2006 [Kapitel 24]; @Bortz2010 [Kapitel 8.1 & 8.2].
{{% /notice %}}