---
title: "Formulierung t-Test"
weight: 211
tags: ["t-test", "mittelwertvergleich"]
---

{{% buttonShare href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

Als Beispiel für die Berechnung eines ungepaarten $t$-tests nehmen wir folgende Frage auf:
Weisen *Frauen* und *Männer* einen unterschiedlichen [Mittelwert](../../../glossar/mittelwert/index.html) bei der wöchentlichen Arbeitszeit auf? Falls ja, sind diese Unterschiede statistisch signifikant?

Der **$t$-test** ist ein [Hypothesentest](../../../glossar/signifikanztest/index.html). In der [Nullhypothese](../../../glossar/nullhypothese/index.html) wird geprüft, dass es keine Unterschiede zwischen den Mittelwerten gibt und in der [Alternativhypothese](../../../glossar/alternativhypothese/index.html), dass es einen Unterschied gibt. Diese Alternativhypothese kann gerichtet ([einseitig](../../../glossar/einseitigertest/index.html)) wie ungerichtet ([zweiseitig](../../../glossar/zweiseitigertest/index.html)) geprüft werden.

Im Beispiel lautet die Nullhypothese
$H_0: \mu_{Männer} = \mu_{Frauen}$

Es gibt keinen Unterschied zwischen *Männer* und *Frauen* in der *mittleren wöchentlichen Arbeitszeit*.

Die ungerichtete Alternativhypothese lautet:
$H_A: \mu_{Männer} \neq \mu_{Frauen}$

Es gibt einen Unterschied zwischen *Männer* und *Frauen* in der *mittleren wöchentlichen Arbeitszeit*.

Alternativ könnte eine gerichtete Alternativhypothese lauten:
$H_{A_{1}}: \mu_{Männer} > \mu_{Frauen}$

*Männer* haben eine höhere *mittlere wöchentliche Arbeitszeit* als *Frauen.*

oder

$H_{A_{2}}: \mu_{Männer} < \mu_{Frauen}$

*Frauen* haben eine höhere *mittlere wöchentliche Arbeitszeit* als *Männer.*

In unserem Beispiel verwenden wir aber eine *ungerichtete* Hypothese: Wir nehmen also in der Nullhypothese an, dass der Mittelwert der *Männer* nicht unterschieden wird von dem der *Frauen.* Bei der *ungerichteten Alternativhypothese* nehmen wir genau das Gegenteil an und führen einen zweiseitigen Test durch. Bei den *gerichteten Alternativhypothesen* wird ein einseitiger Test (je nach Formulierung *links-* oder *rechtsseitig*) ausgeführt.