---
title: "quantitative Sozialforschung"
---

Die quantitative Sozialforschung zeichnet sich durch „ein streng zielorientiertes Vorgehen aus, das die Objektivität (...) der Resultate durch möglichst weitgehende Standardisierung aller Teilschritte anstrebt und das zur Qualitätssicherung die intersubjektive Nachprüfbarkeit des gesamten Prozesses als zentrale Norm postuliert“ (Kromrey 2009: 25).

Ist das Ziel eine Generalisierung von Aussagen werden oftmals Verfahren quantitativer Sozialforschung angewendet. 

{{% buttonGit href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonGit %}} 

{{% buttonGit href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonGit %}}

{{% buttonGit href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonGit %}}

{{% buttonGit href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonGit %}}

{{% buttonGit href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-twitter\" %}} {{% /buttonGit %}}

{{% buttonGit href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonGit %}}