---
title: "Intervall-Skala"
---

dritthöchste Skala der vier Skalenniveaus;
Zusammen mit der Ratio-Skala stellt die Intervall-Skal das metrische Messniveau dar.

Die Intervall-Skala besitzt die Eigenschaften der Nominal-skala (Verlinkung) und Ordinal-Skala (Verlinkung) und zusätzlich haben die Ausprägungen eines Merkmals auf dieser Skala gleich große Abstände. Die Intervall-Skala besitzt allerdings keinen natürlichen Nullpunkt.

Mathematische Operatoren: $=/≠ ; </> ; −/ +$

Messbare Eigenschaften: Häufigkeit, Reihenfolge, Abstand

Beispiel: IQ-Testscore

{{% buttonShare href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}
