---
title: "Mittelwert"
---

auch arithmetisches Mittel; Maß der zentralen Tendenz; stellt den Durchschnittswert der Verteilung dar und daher muss das Merkmal mind. intervallskaliert sein. Es werden alle erhobenen Werte aufsummiert und dann durch die Anzahl der vorhandenen Werte geteilt.
Der Mittelwert wird durch Ausreißer und Extremwerte stark beeinflusst, da alle Werte gleichermaßen und ungewichtet in die Berechnung einbezogen werden.

Formel zur Berechnung: $\bar{x}=\frac {1} {n} * \sum_{i=1} ^n x_i$

{{% buttonShare href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}
