---
title: "Multivariate lineare Regression"
weight: 306
tags: ["multivariat", "regression", "lernvideo"]
bibliography: [../../static/files/publications.bib]
suppress-bibliography: true
link-citations: true
# nocite: "@*" um einfach alle Angaben zu printen am Ende
csl: [../../static/files/apa.csl]
---

Nun erweitern wir die Annahmen auf mehrere [unabhängige Variablen](../../glossar/unabhaengigevariable/index.html). Mit der **Regression** als [multivariate](../../glossar/multivariat/index.html) Analyse können Einflüsse möglicher Drittvariablen kontrolliert werden und es wird Aufschluss über die Abhängigkeitsstrukturen zwischen mehreren [Variablen](../../glossar/variable/index.html) gegeben. Die **Regression** ist daher ein strukturprüfendes Verfahren.

Bei der multivariaten Regression betrachten wir nicht mehr nur eine unabhängige Variable, sondern beziehen mehrere unabhängige Variablen in das Modell hinein. Der Einbezug von unabhängigen Variablen findet stets theoriegeleitet statt. Die Modellformulierung der multivariaten linearen Regression ändert sich daher auf folgende:

$y_i = \beta_0 + \beta_1 \ast x_{1_i} + \beta_2 \ast x_{2_i} + ... + \beta_k \ast x_{k_i} + \varepsilon_i$

Mit $y=(y_1, y_2, ..., y_n), \thinspace x_{k_1} =(x_{k_1}, x_{k_2}, ..., x_{k_n}), \thinspace und \thinspace \varepsilon_i=(\varepsilon_1, \varepsilon_2, ..., \varepsilon_n)$

Die Schätzgleichung des multivariaten Modells lautet wie folgt:

$\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 \ast x_{1_i} + \hat{\beta}_2 \ast x_{2_i} + ... + \hat{\beta}_{k_i} \ast x_{k_i}$

Die Schätzgleichung für die beobachteten Werte des multivariaten Modells lautet in Anpassung an die Modellgleichung wie folgt:

$y_i = \hat{\beta}_0 + \hat{\beta}_1 \ast x_{1_i} + \hat{\beta}_2 \ast x_{2_i} + ... + \hat{\beta}_{k_i} \ast x_{k_i} + \hat{\epsilon}_i$

Es gilt, dass die [abhängige](../../glossar/abhaengigevariable/index.html) und [unabhängige Variablen](../../glossar/unabhaengigevariable/index.html) [metrisch](../../glossar/metrischesskalenniveau/index.html) skaliert sein müssen. Ordinale Variablen, sofern die Annahme gleicher Abstände zwischen den Ausprägungen stimmt, können in das Modell übernommen werden (sie werden dann als [pseudo-metrisch](../../glossar/pseudometrisch/index.html) behandelt). Auch bei der multivariaten linearen Regression wird das [OLS-Verfahren](../../glossar/ols/index.html) zur Berechnung der Regression genutzt.

Kommen wir wieder auf unser Beispiel der *Zufriedenheit mit der Demokratie* zurück: im [bivariaten](../../glossar/bivariat/index.html) Fall wollten wir die *Zufriedenheit mit der Demokratie* über die *Zufriedenheit mit der ökonomischen Leistung* einer Person erklären. Als weiteren erklärenden Faktor könnten wir annehmen, dass das Einkommen einer Person ebenfalls Einfluss auf die Höhe der *Zufriedenheit mit der Demokratie* hat. Damit würde sich folgende Gleichung für die Schätzung des *Zufriedenheit mit der Demokratie* ergeben:

$satdem_i= \beta_0 + \beta_1 \ast sateco_i + \beta_2 \ast Einkommen_i + e_i$

Wir nehmen also an, dass sich die *Zufriedenheit mit der Demokratie* einer Person über die unabhängigen Variablen *Zufriedenheit mit der ökonomischen Leistung* und *Einkommen* dieser Person erklären lässt.

Im Nachfolgenden wird nun die Interpretation der wichtigsten **Kennzahlen einer Regression** am genannte Beispiel erklärt.

{{% notice tip %}}
Siehe auch: @Urban2011 [Kapitel 2.3]; @Fromm2010 [Kapitel 3.2.2].
{{% /notice %}}