---
title: "Einführung"
weight: 301
tags: ["regression", "bivariat"]
bibliography: [../../static/files/publications.bib]
suppress-bibliography: true
link-citations: true
# nocite: "@*" um einfach alle Angaben zu printen am Ende
csl: [../../static/files/apa.csl]
---

{{% buttonShare href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

Im ersten Schritt werden nun die **mathematischen Grundlagen** des Verfahrens der **linearen Regression** am Beispiel einer **bivariaten linearen Regression** vorgestellt. Aufbauend darauf werden die Grundlagen auf eine **multivariate lineare Regression** übertragen und die Interpretation der **wichtigsten Kennzahlen** vorgestellt. Abschließend wird zum besseren Verständnis ein **Praxisbeispiel** aktueller Forschung der empirischen Demokratieforschung dargestellt.

Die **Regressionsanalyse** ist eine statistische Methode, um die Beziehungsstruktur zwischen mehreren [Variablen](../../glossar/variable/index.html) zu untersuchen. Dabei findet eine *Informationsreduktion* statt, so dass die Untersuchung auf wenige **Kennzahlen** beschränkt werden kann. Mit der **Regressionsanalyse** kann die Wirkung einer oder mehrerer [unabhängiger Variable(n)](../../glossar/unabhaengigevariable/index.html) auf eine [abhängige Variable](../../glossar/abhaengigevariable/index.html) in Bezug auf die Richtung und die Stärke des Einflusses überprüft werden.

Im Unterschied zur [Korrelation](../../glossar/korrelation/index.html) wird bei der **Regressionsanalyse** die [Kausalität](../../glossar/kausalitaet/index.html) überprüft. Die Richtung des Einflusses wird theoriegeleitet festgelegt, von der unabhängigen auf die abhängige Variable. [Inferenzstatistisch](../../glossar/inferenzstatistik/index.html) wird zusätzlich überprüft, ob dieser Einfluss [signifikant](../../glossar/signifikanztest/index.html) ist, also ob er in der [Grundgesamtheit](../../glossar/grundgesamtheit/index.html) der [Stichprobe](../../glossar/stichprobe/index.html) als wahrscheinlich gilt.

Allgemein ausgedrückt können mit der **Regressionsanalyse** zwei verwandte Fragen beantwortet werden:

- Wie gut erklären bestimmte Faktoren (unabhängige Variablen) die [Varianz](../../glossar/varianz/index.html) einer abhängigen Variable?

- Welchen Einfluss üben die einzelnen Faktoren auf diese abhängige Variable unter Konstanthalten (Kontrolle) des Einflusses der anderen unabhängigen Variablen aus?

Die **multivariate lineare Regression** stellt dabei eine grundsätzliche Analysemethode dar. Mit der (**multivariaten**) **linearen Regression** wird versucht, eine metrische Variable über eine Linearkombination mehrerer anderer Variablen (metrisch) darzustellen und kausal zu erklären.

Mithilfe eines **Regressionsmodells** lassen sich aus der Theorie hergeleitete Hypothesen über eine Beeinflussungsstruktur bestimmter Variablen auf andere Variablen überprüfen. Für die Sozialwissenschaften ist dies ein geeignetes Verfahren, da in der Regel mehrere Variablen einen Einfluss auf eine abhängige Variable ausüben, die wir in eine **Regressionsanalyse** integrieren können. Es werden dabei verschiedene **Arten der Regression** in Abhängigkeit des [Skalenniveaus](../../glossar/skalenniveau/index.html) der abhängigen Variable unterschieden:

- **lineare Regression**

- **logistische Regression**

- **Probit-Regression**

Bei der **linearen Regression** wird ein linearer Zusammenhang zwischen abhängiger Variable und unabhängigen Variablen angenommen. Es stellt somit eine Weiterentwicklung der bivariaten Korrelationsanalyse dar. Die abhängige Variable muss ein metrisches Skalenniveau aufweisen.

Die **logistische Regression** wird für [dichotome](../../glossar/dichotom/index.html) abhängige Variablen genutzt ([nominale Skala](../../glossar/nominalskala/index.html)), da der Zusammenhang sich nur logistisch und nicht linear darstellen lässt. Die **Probit-Regression** erweitert die **logistische Regression** auf [kategoriale Variablen](../../glossar/kategorialesskalenniveau/indexhtml) mit mehr als zwei [Ausprägungen](../../glossar/merkmalsauspraegung/index.html). Sowohl die **logistische** und **Probit-Regression** sind *fortgeschrittene* Verfahren quantitativer Analysetechniken. Sie werden daher in diesem Lernmodul nicht näher behandelt.

{{% notice tip %}}
Siehe auch: @Urban2011; @Fromm2010 [Kapitel 3]; @Janssen2013 [Kapitel 17].
{{% /notice %}}