---
title: "Beispiele"
weight: 114
tags: ["konfidenzintervall", "signifikanz", "hypothesentest", "lernvideo"]
---

{{% buttonShare href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

Im Folgenden werden zwei Beispiele berechnet, die auch in dem Lernvideo nochmals erklärt werden.

## bekanntes $\sigma_x$
Wir haben eine Umfrage mit $2064$ Befragten ($n=2064$) mit einem Durchschnittsalter von $42.7$ Jahren ($\bar{x}_{Alter} = 42.7$) und einer Standardabweichung in der Grundgesamtheit von $11.2$ Jahren ($\sigma_{Alter} = 11.2$). Wir wollen das $90\%$-Konfidenzintervall berechnen.

$n = 2064$

$\bar{x}_{Alter} = 42.7$

$\sigma_{Alter} = 11.2$

$z_{0.95} = 1.645$

Geschätzter Standardfehler der Grundgesamtheit ist daher:

$\hat{\sigma}_\bar{x} = \frac{\sigma_x}{\sqrt{n}} = \frac{11.2}{\sqrt{2064}} \approx 0.25$

Formel zur Berechnung des Intervalls:

$\bar{x} \pm z_{1-\frac{\alpha}{2}} \ast {\sigma_{\bar{x}}}$

Berechnung der Grenzen:

$x_U = \bar{x} - z_{1-\frac{0.1}{2}} \ast {\sigma_{\bar{x}}} = 42.7 - 1.645 * \frac{11.2}{\sqrt{2064}} \approx 42.7 - 0.406 \approx 42.294$

$x_O = \bar{x} - z_{1-\frac{0.1}{2}} \ast {\sigma_{\bar{x}}} = 42.7 + 1.645 * \frac{11.2}{\sqrt{2064}} \approx 42.7 + 0.406 \approx 43.106$

Das $90\%$-Konfidenzintervall um den Mittelwert $\bar{x} = 42.7$ geht von $[42.294, 43.106]$.

Hier ein weiteres Beispiel im Video:

<center>
<iframe src="https://flash.uni-giessen.de/vod/c097e06b0af84d5d002e7219e02a41da.mp4" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen referrerpolicy="noreferrer"></iframe>
</center>

## Unbekanntes $\sigma_x$ ($z$-Verteilung)
Wir haben eine Umfrage mit $1500$ Befragten ($n=1500$) mit einem Durchschnittsalter von $34.5$ Jahren ($\bar{x}_{Alter} = 34.5$) und einer Standardabweichung in der Stichprobe von $4$ Jahren ($s_{Alter} = 4$). Wir wollen das $99\%$-Konfidenzintervall berechnen.

$n = 1500$

$\bar{x}_{Alter} = 34.5$

$s_{Alter} = 4$

$z_{0.995} = 2.58$

Zuerst muss nun die Standardabweichung in der Grundgesamtheit geschätzt werden ($\hat{\sigma}_x$):

$\hat{\sigma}_x = \sqrt{\hat{\sigma}_x^2} = \sqrt{\frac{ \sum\limits_{i=1}^n (x_{i} - \bar{x})^2} {n-1}} = \sqrt{s^2} = s = 4$

Danach muss der Standardfehler geschätzt werden:

$\hat{\sigma}_{\bar{x}} = \frac {\hat{\sigma}_{x}}{\sqrt{n}} = \frac{4}{1500} \approx 0.003$

Nun kann das Intervall berechnet werden:

$x_U = \bar{x} - z_{1-\frac{\alpha}{2}} \ast {\hat{\sigma}_{\bar{x}}} = 34.5 - 2.58 * 0.003 \approx 34.492$

$x_O = \bar{x} + z_{1-\frac{\alpha}{2}} \ast {\hat{\sigma}_{\bar{x}}}= 34.5 + 2.58 * 0.003 \approx 34.508$

Das $99\%$-Konfidenzintervall um den Mittelwert $\bar{x} = 34.5$ geht von $[34.492, 34.508]$.

Hier ein weiteres Beispiel im Video:

<center>
<iframe src="https://flash.uni-giessen.de/vod/0e24dca3f43a491d61f38208b32890d5.mp4" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen referrerpolicy="noreferrer"></iframe>
</center>


## Unbekanntes $\sigma_x$ ($t$-Verteilung)
Wir haben eine Umfrage mit $101$ Befragten ($n=101$) mit einem Durchschnittsalter von $51.4$ Jahren ($\bar{x}_{Alter} = 51.4$) und einer Standardabweichung in der Stichprobe von $4.5$ Jahren ($s_{Alter} = 4.5$). Wir wollen das $95\%$-Konfidenzintervall berechnen.

$n = 101$

$\bar{x}_{Alter} = 51.4$

$s_{Alter} = 4.5$

$t_{(0.975, 100)} = 1.984$

Zuerst muss hier nun wieder die Standardabweichung der Grundgesamtheit geschätzt werden:

$\hat{\sigma}_x = \sqrt{\hat{\sigma}_x^2} = \sqrt{\frac{ \sum\limits_{i=1}^n (x_{i} - \bar{x})^2} {n-1}} = \sqrt{s^2} = s = 4.5$

Danach muss der Standardfehler geschätzt werden:

$\hat{\sigma}_{\bar{x}} = \frac {\hat{\sigma}_{x}}{\sqrt{n}} = \frac{4.5}{101} \approx 0.045$

Nun kann das Intervall berechnet werden:

$x_U = \bar{x} - t_{(0.975, 100)} \ast {\hat{\sigma}_{\bar{x}}} = 51.4 - 1.984 * 0.045 \approx 51.311$

$x_O = \bar{x} + t_{(0.975, 100)} \ast {\hat{\sigma}_{\bar{x}}}= 51.4 + 1.984 * 0.045 \approx 51.579$

Das $95\%$-Konfidenzintervall um den Mittelwert $\bar{x} = 51.4$ geht von $[51.311, 51.579]$.

Hier ein weiteres Beispiel im Video:

<center>
<iframe src="https://flash.uni-giessen.de/vod/34ccf838cda7ba37b34f6d48ce6a0546.mp4" width="640" height="480" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen referrerpolicy="noreferrer"></iframe>
</center>